config/routes.rb
Webstragram::Application.routes.draw do
  get "feeds/get_feeds"
  get "feeds/more"
  get "photos/more"
  get "populars/more"

  resources :photos

  resources :populars

  get "oauth/connect"

  get "oauth/callback"

  resources :feeds
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  Instagram.configure do |config|
    config.client_id = Rails.configuration.CLIENT_ID
    config.client_secret = Rails.configuration.SECRET_ID
  end
  
  def verify_user    
    @user = Instagram.client(:access_token => session[:access_token])
    
    if @user.access_token === nil 
      redirect_to :controller => "oauth", :action => "connect"        
    else
      return @user
    end  
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  # GET /feeds
  # GET /feeds.json
  def index
    ## verify login logger.debug ">>>>>>> #{user.access_token}"    
    user = verify_user
    
    @feeds = user.user_media_feed(:count => 15) 
    
    logger.debug ">>>>>> #{@feeds.to_yaml}"
    session[:next_url] = @feeds.pagination.next_max_id
            
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feeds }
    end
  end
  
  def get_feeds
    
    user = verify_user
    @feeds = user.user_media_feed(:count => 15, :max_id => session[:next_url])
    session[:next_url] = @feeds.pagination.next_max_id
        
    respond_to do |format|
      format.json { render json: @feeds.data }
    end
  end
  
  def more
    user = verify_user
    @feeds = user.user_media_feed(:count => 15, :max_id => session[:next_url])
    session[:next_url] = @feeds.pagination.next_max_id
       
    render :template => "feeds/index"
    
  end
end

app/controllers/oauth_controller.rb
class OauthController < ApplicationController
  
  def connect
    redirect_to Instagram.authorize_url(:redirect_uri => Rails.configuration.CALLBACK)
  end
  
  def callback
    response = Instagram.get_access_token(params[:code], :redirect_uri => Rails.configuration.CALLBACK)
    session[:access_token] = response.access_token
    redirect_to "/feeds"
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.json
  def index
    user = verify_user
    
    @photos = user.user_recent_media
    
    #logger.debug "#{@photos.to_yaml}"
    
    #session[:next_url_photos] = @photos.pagination.next_max_id
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end
  
  def more
    #user = verify_user
    
    #@photos = user.user_media_feed(:count => 15, :max_id => session[:next_url_photos])
    #session[:next_url_photos] = @photos.pagination.next_max_id
       
    #render :template => "photos/index"
    
  end
  def show
      user = verify_user
      
      @photo = user.media_item(params[:id])
      
      #images.standard_resolution - caption.text - location.name - link  - caption.from.username - caption.from.full_name
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @photo }
      end
  end
end

app/controllers/populars_controller.rb
class PopularsController < ApplicationController
  # GET /populars
  # GET /populars.json
  def index
    
    user = verify_user    
    
    @populars = user.media_popular(:count => 15)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @populars }
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/oauth_helper.rb
module OauthHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/populars_helper.rb
module PopularsHelper
end

app/views/feeds/index.html.erb
<% for item in @feeds.data %>
<div class="span3" >
	<div class="photos">
	<div class="photo_information">
		<div class="photo_user">
			<a href="#"><img src="<%= item.user.profile_picture %>"></a>	
		</div>
		<div class="name_user">
			<strong>
				<a href="#"><%= item.user.username %></a>
			</strong>
			<br>
			<span><%= item.user.full_name %></span>
		</div>	
	</div>
	<div class="photo">
		<a href="<%= photos_url + '/' + item.id %>">
			<img src="<%= item.images.low_resolution.url %>">
		</a>	
	</div>
	<div class="photo_like">
		<i class="icon-heart"><strong> <%= item.likes['count'] %></strong></i>
		<strong>-</strong>
		<i class="icon-comment"><strong> <%= item.comments['count'] %></strong></i>
	</div>
	<span class="post_time"><%= time_ago_in_words Time.at(item.created_time.to_i) %> ago</span>
	<strong>/</strong>
	<span class="filter"><%= item.filter %></span>
	</div>
</div>

<% end %>
<div class="span12">
	<a href="<%= feeds_more_url	 %>" class="btn btn-primary btn-large">Load more...</a>
</div>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webstragram</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">
	      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </a>
	      <a class="brand" href="#">WebGram</a>
	      <div class="nav-collapse">
	        <ul class="nav">
	          <li><%= link_to "Browse Feed", feeds_path %></li>
	          <li><%= link_to "Browse Popular", populars_path %></li>	
			  <li><%= link_to "My Photos", photos_path %></li>		
	        </ul>
	      </div>
	    </div>
	  </div>
	</div>

		<div class="container">
		  <div class="row">
		    <div class="span12"><%= yield %></div>
		  </div>
		</div>

</body>
</html>

app/views/layouts/photo.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webstragram</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">
	      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </a>
	      <a class="brand" href="#">WebGram</a>
	      <div class="nav-collapse">
	        <ul class="nav">
	          <li><%= link_to "Browse Feed", feeds_path %></li>
	          <li><%= link_to "Browse Popular", populars_path %></li>	
			  <li><%= link_to "My Photos", photos_path %></li>		
	        </ul>
	      </div>
	    </div>
	  </div>
	</div>

		<div class="container-fluid">
		  <div class="row-fluid">
		    <div class="span10">
		      <%= yield %>
		    </div>
		    <div class="span2">
		      <!--Body content-->
		    </div>
		  </div>
		</div>

</body>
</html>

app/views/oauth/callback.html.erb
<h1>Oauth#callback</h1>
<p>Find me in app/views/oauth/callback.html.erb</p>

app/views/oauth/connect.html.erb
<h1>Oauth#connect</h1>
<p>Find me in app/views/oauth/connect.html.erb</p>

app/views/photos/index.html.erb
<% for item in @photos %>

<div class="span3" >
	<div class="photos">
	<div class="photo_information">
		<div class="photo_user">
			<a href="#"><img src="<%= item.user.profile_picture %>"></a>	
		</div>
		<div class="name_user">
			<strong>
				<a href="#"><%= item.user.username %></a>
			</strong>
			<br>
			<span><%= item.user.full_name %></span>
		</div>	
	</div>
	<div class="photo">
		<a href="<%= photos_url + '/' + item.id %>">
			<img src="<%= item.images.low_resolution.url %>">
		</a>	
	</div>
	<div class="photo_like">
		<i class="icon-heart"><strong> <%= item.likes['count'] %></strong></i>
		<strong>-</strong>
		<i class="icon-comment"><strong> <%= item.comments['count'] %></strong></i>
	</div>
	<span class="post_time"><%= time_ago_in_words Time.at(item.created_time.to_i) %> ago</span>
	<strong>/</strong>
	<span class="filter"><%= item.filter %></span>
	</div>
</div>
	
<% end %>

app/views/photos/show.html.erb
<div class="container-fluid" >
	<div class="row-fluid" >
		<div class="span8" >
			<div class="photos">
			<div class="text">
				<% if @photo.caption != nil%>
					<i><%= @photo.caption.text%></i>	
				<% end %>	
			</div>	
			<div class="photo_one">
					<img src="<%= @photo.images.standard_resolution.url %>">
			</div>

			</div>
		</div>
		<div class="span4" >
			<div class="photo_information">
				<div class="photo_user">
					<img src="<%= @photo.user.profile_picture %>">	
				</div>
				<div class="name_user">
					<strong><%= @photo.user.full_name %></strong>
				</div>	
			</div>
	
			<span class="post_time"><%= time_ago_in_words Time.at(@photo.created_time.to_i) %> ago</span>
			<strong>/</strong>
			<span class="filter"><%= @photo.filter %></span>
			
			<div class="photo_like">
				<i class="icon-heart"> Likes: <strong> <%= @photo.likes['count'] %></strong></i>
				<br/>
				<i class="icon-comment"> Comments: <strong> <%= @photo.comments['count'] %></strong></i>
				<br/>
				<i class="icon-picture"> Filter: <strong> <%= @photo.filter %></strong></i>
			</div>
			<div class="share">
					<iframe  allowtransparency="true" frameborder="0" scrolling="no" src="//platform.twitter.com/widgets/tweet_button.html?lang=en&amp;url=<%= @photo.linke %>&amp;text=instagram&amp;count=horizontal&amp;via=instagram" style="border:none; overflow:hidden; width:100px; height:35px;" ></iframe>
					<iframe src="//www.facebook.com/plugins/like.php?href=<%= @photo.link %>&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font=arial&amp;height=35" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:100px; height:35px;" allowTransparency="true"></iframe>
			</div>
		</div>	
	</div>
</div>	

app/views/populars/index.html.erb
<% for item in @populars %>

<div class="span3" >
	<div class="photos">
	<div class="photo_information">
		<div class="photo_user">
			<a href="#"><img src="<%= item.user.profile_picture %>" ></a>	
		</div>
		<div class="name_user">
			<strong>
				<a href="#"><%= item.user.username %></a>
			</strong>
			<br>
			<span><%= item.user.full_name %></span>
		</div>	
	</div>
	<div class="photo">
		<a href="<%= photos_url + '/' + item.id %>">
			<img src="<%= item.images.low_resolution.url %>">
		</a>	
	</div>
	<div class="photo_like">
		<i class="icon-heart"><strong> <%= item.likes['count'] %></strong></i>
		<strong>-</strong>
		<i class="icon-comment"><strong> <%= item.comments['count'] %></strong></i>
	</div>
	<span class="post_time"><%= time_ago_in_words Time.at(item.created_time.to_i) %> ago</span>
	<strong>/</strong>
	<span class="filter"><%= item.filter %></span>
	</div>
</div>
	
<% end %>